import { Presentation, PresentationFile } from "file:///C:/Users/CJSCOPE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/@oai/artifact-tool/dist/artifact_tool.mjs";
const p = Presentation.create({slideSize:{width:1280,height:720}});
const s = p.slides.add();
s.background.fill = "#FFFFFF";
console.log("rect");
s.shapes.add({geometry:"rect",position:{left:100,top:100,width:200,height:100},fill:"#F1F2F4",line:{style:"solid",fill:"#B8BCC4",width:2}});
console.log("line");
s.shapes.add({geometry:"line",position:{left:100,top:240,width:200,height:0},fill:"none",line:{style:"solid",fill:"#3D8DFF",width:2}});
console.log("ellipse");
s.shapes.add({geometry:"ellipse",position:{left:180,top:300,width:26,height:26},fill:"#F28C28",line:{style:"solid",fill:"#F28C28",width:1}});
console.log("textbox");
const t=s.shapes.add({geometry:"textbox",position:{left:100,top:350,width:400,height:100},fill:"none",line:{style:"solid",fill:"none",width:0}});
t.text="Obstacles\nand levels";
console.log("style");
t.text.style={fontSize:64,bold:true,color:"#111111",alignment:"center",verticalAlignment:"middle"};
console.log("arrow");
s.shapes.add({geometry:"rightArrow",position:{left:500,top:300,width:60,height:30},fill:"#D9F0FB",line:{style:"solid",fill:"#D9F0FB",width:1}});
console.log("export");
const pptx=await PresentationFile.exportPptx(p); await pptx.save("C:/Users/CJSCOPE/Desktop/PythonSDD/day2_slides_build/test-shapes.pptx"); console.log("saved");